version: '2'

services:
  db:
    image: mongo:latest
    container_name: vm_mongoDB
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=technicalTest
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=default
    volumes:
    # NOTE: Since this project is currently run on a virtual machine with a shared folder, it is causing trouble
    # to add the database to the project so is better to map it to the host os directly. This is a known problem of
    # mongo in virtual environments
      - /data/db:/data/db
    command: mongod --auth --dbpath /data/db
  nginx:
    image: nginx:latest
    container_name: vm_nginx
    volumes: 
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 8080:8080
    depends_on:
      - db
      - feedback
  feedback:
    build: './feedback'
    ports: 
      - 3001:3000
    depends_on:
      - db
    volumes:
      - ./feedback/:/var/www/api/